package utils

func HandleError(err error) {
	if err != nil {
		LogError("‚ùå ERROR", err.Error())
		panic("")
	}
}
